    <!--SECCION PIE DE PAGINA(DEBE SER IGUAL PARA TODAS LAS PAGINAS)-->
    <footer class="footer">
      <!-- Redes sociales -->
      <section class="buttons">
        <a href="https://www.facebook.com/loberiaturismo" class="fab fa-facebook fa-2x"></a>
        <a href="https://twitter.com/loberiaturismo" class="fab fa-twitter fa-2x"></a>
        <a href="https://www.instagram.com/muniloberia/?hl=es-la" class="fab fa-instagram fa-2x"></a>
        <a href="" class="fab fa-whatsapp fa-2x"></a>
      </section>
      <script src="./js/mensajeReservacion.js"></script>
      <script src="./js/formulario.js"></script>
      <script src="./js/form_dispo.js"></script>
      <script src="./js/editUser.js"></script>
      <script src="./js/editPrecios.js"></script>
    </footer>
    </div> <!-- cierre de .wrapper -->
</body>
</html>
