
    <!--SECCION PIE DE PAGINA(DEBE SER IGUAL PARA TODAS LAS PAGINAS)-->
    <footer class="footer">
      <!-- Redes sociales -->
      <section class="buttons">
        <a href="https://www.facebook.com/loberiaturismo" class="fa fa-facebook"></a>
        <a href="https://twitter.com/loberiaturismo" class="fa fa-twitter"></a>
        <a href="https://www.instagram.com/muniloberia/?hl=es-la" class="fa fa-instagram"></a>
        <a href="" class="fa fa-whatsapp"></a>
      </section>
      <script src="./js/formulario.js"></script>
    <script src="./js/form_dispo.js"></script>
    <script src="./js/editUser.js"></script>
    <script src="./js/editPrecios.js"></script>
    </footer>

    </body>
    </html>