
    <!--SECCION PIE DE PAGINA(DEBE SER IGUAL PARA TODAS LAS PAGINAS)-->
    <footer class="footer">
      <!-- Redes sociales -->
      <section class="buttons">
        <a href="https://www.facebook.com/loberiaturismo" class="fa fa-facebook"></a>
        <a href="https://twitter.com/loberiaturismo" class="fa fa-twitter"></a>
        <a href="https://www.youtube.com/channel/UCsAuGNjsbHgbGKn-1rG8mGA" class="fa fa-instagram"></a>
        <a href="https://www.instagram.com/muniloberia/?hl=es-la" class="fa fa-whatsapp"></a>
      </section>
    </footer>