<br>
<?php if (!empty($mensaje)) : ?>
    <div class="mensaje <?= $tipo_mensaje; ?>">
        <p><?= $mensaje; ?></p>
        <?php if ($tipo_mensaje == 'exito') : ?>
            <?php if($mensaje_qr == true) : ?>
                    <img src="./img/qr/codigo_qr.png" alt="QR de confirmación" style="width: 250px; display: block; margin: 10px auto;">
                    <p>Podrá realizar el pago de la reservación a través del siguiente QR. No olvide comunicarse por WhatsApp.</p>
            <?php else : ?>
                    <p>El cobro de la reservación se hará en la base del campamento.</p>
            <?php endif; ?>
            <a href="https://wa.me/+5492262301388" target="_blank" class="btn btn-success" onclick="cerrarMensajeYResetear()">
                <i class="fab fa-whatsapp"></i> Confirmar
            </a>
            <button onclick="cerrarMensajeYResetear()" class="btn btn-danger">Salir</button>
        <?php else : ?>
            <button onclick="cerrarMensajeYResetear()" class="btn btn-danger">Aceptar</button>
        <?php endif; ?>
    </div>
<?php endif; ?>
<form action="generar_reservacion" class="container mt-4" id="buscadorForm" method="post">

    <!-- Datos personales -->
    <div class="card mb-4">
        <div class="card-header text-white  fw-bold fs-4" style="background-color: #57af31;">
            Datos del titular de la reserva
        </div>
        <div class="card-body row g-3">
            <div class="col-md-4">
                <label class="form-label">Nombre</label>
                <input type="text" class="form-control" value="<?php echo $nombre; ?>" name="nombre" required>
            </div>
            <div class="col-md-4">
                <label class="form-label">Apellido</label>
                <input type="text" class="form-control" value="<?php echo $apellido; ?>" name="apellido" required>
            </div>
            <div class="col-md-4">
                <label class="form-label">DNI</label>
                <input type="number" class="form-control" value="<?php echo $dni; ?>" name="dni" required>
            </div>
        </div>
    </div>

    <!-- Estadia -->
    <div class="card mb-4">
        <div class="card-header text-white fw-bold fs-4" style="background-color: #57af31;">
            Información de la estadía
        </div>
        <div class="card-body row g-3">
            <div class="col-md-4">
                <label class="form-label">Fecha de inicio</label>
                <input type="date" class="form-control" id="inicio" name="inicio" value="<?php echo date("Y-m-d"); ?>" required>
            </div>
            <div class="col-md-4">
                <label class="form-label">Fecha de fin</label>
                <input type="date" class="form-control" id="fecha_fin" name="fecha_fin" required>
            </div>
            <div class="col-md-4">
                <label class="form-label">Tipo de estadía</label>
                <select class="form-select" name="tipo_estadia" required>
                    <option value="acampar">Acampar</option>
                    <option value="pasar_dia">Pasar el día</option>
                </select>
            </div>
        </div>
    </div>
 <!-- Pago -->
    <div class="card mb-4">
        <div class="card-header text-white fw-bold fs-4" style="background-color: #57af31;">
            Información de Pago de la estadía
        </div>
        <div class="card-body row g-3">
            <div class="col-md-4">
                <label class="form-label">Forma de Pago: </label>
                <select class="form-select" name="tipo_pago" required>
                    <option value="efectivo">En efectivo</option>
                    <option value="transferencia">Por Transferencia</option>
                </select>
            </div>
        </div>
    </div>
    <!-- Personas -->
    <div class="card mb-4">
        <div class="card-header text-white fw-bold fs-4" style="background-color: #57af31;">
            Cantidad de personas por rango etario
        </div>
        <div class="card-body row g-3">
            <div class="col-md-4">
                <label class="form-label">Menores de 4 años</label>
                <select class="form-select" name="menores">
                    <?php for ($i = 0; $i <= 6; $i++) echo "<option value=\"$i\">$i</option>"; ?>
                </select>
            </div>
            <div class="col-md-4">
                <label class="form-label">De 4 a 12 años</label>
                <select class="form-select" name="cuatroDoce">
                    <?php for ($i = 0; $i <= 10; $i++) echo "<option value=\"$i\">$i</option>"; ?>
                </select>
            </div>
            <div class="col-md-4">
                <label class="form-label">12 años o más</label>
                <select class="form-select" name="doceMas">
                    <?php for ($i = 1; $i <= 10; $i++) echo "<option value=\"$i\">$i</option>"; ?>
                </select>
            </div>
        </div>
    </div>

    <!-- Vehículo -->
    <div class="card mb-4">
        <div class="card-header text-white fw-bold fs-4" style="background-color: #57af31;">
            Vehículo
        </div>
        <div class="card-body">
            <label class="form-label">Tipo de vehículo</label>
            <select class="form-select" name="tipo_de_vehiculo" required>
                <option value="Auto">Auto</option>
                <option value="Camioneta">Camioneta</option>
                <option value="Motorhome">Motorhome</option>
                <option value="Casilla">Casilla</option>
            </select>
        </div>
    </div>

    <!-- Características de parcela -->
    <div class="card mb-4">
        <div class="card-header text-white fw-bold fs-4" style="background-color: #57af31;">
            Características de la parcela
        </div>
        <div class="card-body row">
            <div class="col-md-6">
                <div class="form-check">
                    <input class="form-check-input" name="caracteristicas[]" type="checkbox" value="fogon" id="fogon">
                    <label class="form-check-label" for="fogon">Con Fogón</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" name="caracteristicas[]" type="checkbox" value="tomaElectrica" id="electrica">
                    <label class="form-check-label" for="electrica">Con Toma Eléctrica</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" name="caracteristicas[]" type="checkbox" value="sombra" id="sombra">
                    <label class="form-check-label" for="sombra">Con Sombra</label>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-check">
                    <input class="form-check-input" name="caracteristicas[]" type="checkbox" value="agua" id="agua">
                    <label class="form-check-label" for="agua">Con Agua</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" name="caracteristicas[]" type="checkbox" value="con_ducha" id="ducha">
                    <label class="form-check-label" for="ducha">Con Ducha</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" checked disabled id="sanitario">
                    <label class="form-check-label" for="sanitario">✔ Con Sanitario (Siempre incluido)</label>
                </div>
            </div>
        </div>
    </div>

    <!-- Botón de envío -->
    <div class="text-center">
        <button type="submit" class="btn btn-lg px-5" style="background-color: #57af31; color: white;">Reservar</button>
    </div>

</form>
<br>