

<?php if (!empty($mensaje)) : ?>
    <div class="mensaje <?= $tipo_mensaje; ?>">
        <p><?= $mensaje; ?></p>
        <?php if ($tipo_mensaje == 'exito') : ?>
            <a href="https://wa.me/+5492262301388" target="_blank" class="btn btn-success" onclick="cerrarMensajeYResetear()"> 
            <i class="fab fa-whatsapp"></i> Confirmar
            </a>
            <button onclick="cerrarMensajeYResetear()" class="btn btn-danger">Salir</button>
        <?php else : ?>
            <button onclick="cerrarMensajeYResetear()" class="btn btn-danger">Aceptar</button>
        <?php endif; ?>
    </div>
<?php endif; ?>
        <form action="generar_reservacion" class="form-inline formulario" id="buscadorForm" method="post">
            <div class="form-group">
                <div>
                    <label>Reservacion a Nombre de :</label>
                    <br>
                    <label>Nombre :</label>
                    <input type="text" value="<?php echo $nombre; ?>" name="nombre">
                    <label>Apellido :</label>
                    <input type="text" value="<?php echo $apellido; ?>" name="apellido">
                    <label>Dni :</label>
                    <input type="number" value="<?php echo $dni; ?>" name="dni">
                </div>
                <div>
                </div>
                <div class="form-group">
                    <label>Tiempo de Estadia </label>
                    <div class="form-group">
                        <label for="inicio">Fecha de inicio:</label>
                        <input type="date" id="inicio" value="<?php echo date("Y-m-d"); ?>" name="inicio" required />
                    </div>
                    <div class="form-group">
                        <label for="fecha_fin">Fecha de fin:</label>
                        <input type="date" id="fecha_fin" name="fecha_fin" required />
                    </div>
                </div>
                <div class="edad-selector">
                    <div> <label for="menores">Menores de 4 años:</label>
                        <select id="menores" name="menores">
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                        </select>
                    </div>
                    <div> <label for="cuatroDoce">De 4 a 12 años:</label>
                        <select id="cuatroDoce" name="cuatroDoce">
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>
                    <div>
                        <label for="doceMas">12 años y más:</label>
                        <select id="doceMas" name="doceMas">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="tipo_de_vehiculo">Tipo de vehículo:</label>
                        <select class="form_vehiculo" id="tipo_de_vehiculo" name="tipo_de_vehiculo" required>
                            <option value="Auto">Auto</option>
                            <option value="Camioneta">Camioneta</option>
                            <option value="Motorhome">Motorhome</option>
                            <option value="Casilla">Casilla</option>

                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label>Características de la parcela:</label>
                        <div>
                            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox1" value="fogon">
                            <label for="inlineCheckbox1">Con Fogón</label>
                        </div>
                        <div>
                            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox2" value="tomaElectrica">
                            <label for="inlineCheckbox2">Con Toma Eléctrica</label>
                        </div>
                        <div>
                            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox3" value="sombra">
                            <label for="inlineCheckbox3">Con Sombra</label>
                        </div>
                        <div>
                            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox4" value="agua">
                            <label for="inlineCheckbox4">Con Agua</label>
                        </div>
                        <div>
                            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox5" value="con_ducha">
                            <label for="inlineCheckbox4">Con Ducha</label>
                        </div>
                        <div>
                            <input class="form-check form-check-inline" type="checkbox" id="inlineCheckbox6" checked disabled>
                            <label for="inlineCheckbox6">✔ Con Sanitario (Siempre incluido, puede estar cerca o ser químico)</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <button type="submit" class="btn btn-success">Reservar</button>
                </div>
        </form>
        <br>
