 <!--SECCION DEL FORMULARIO DE REGISTRO-->
 <div class="overlay" id="overlay">
      <div class="form-container">
        <h2>Registro</h2>
        <form id="registrationForm" method="$_POST">
          <input type="number" id="dni" name="dni" placeholder="DNI" required />
          <input
            type="text"
            id="name"
            name="name"
            placeholder="Nombre"
            required
          />
          <input
            type="text"
            id="apellido"
            name="apellido"
            placeholder="Apellido"
            required
          />
          <input
            type="number"
            id="phone"
            name="phone"
            placeholder="Celular"
            required
          />
          <input
            type="email"
            id="email"
            name="email"
            placeholder="E-mail"
            required
          />
          <input
            type="text"
            id="location"
            name="location"
            placeholder="Localidad"
            required
          />
          <button type="submit">Registrarse</button>
          <button type="button" class="cancel" id="cancelBtn">Cancelar</button>
        </form>
      </div>
    </div>