<main>
  <section>
  <form id="buscadorForm">
        <label for="inicio">Fecha de inicio:</label>
        <input type="date" id="inicio" name="inicio" required />
        <label for="fecha_fin">Fecha de fin:</label>
        <input type="date" id="fecha_fin" name="fecha_fin" required />
        <label for="personas">Cantidad de personas:</label>
        <input type="number" id="personas" name="personas" required />
        <label for="tipo_de_vehiculo">Tipo de vehículo:</label>
        <select id="tipo_de_vehiculo" name="tipo_de_vehiculo" required>
          <option value="auto">Auto</option>
          <option value="camioneta">Camioneta</option>
          <option value="motorhome">Motorhome</option>
        </select>
        <label for="caracteristicas">Características de la parcela:</label>
        <select id="caracteristicas" name="caracteristicas" required>
          <option value="fogon">Con fogón</option>
          <option value="tomaElectrica">Con toma eléctrica</option>
          <option value="accesibilidad">Con accesibilidad</option>
        </select>
        <button type="submit">Buscar</button>
      </form>
      <div id="results"></div>
    </section>
       

      </main>
      
