<form action="buscarParcelasDispo" id="buscadorForm" method="post" onsubmit="return validarForm()">
      <div class="form-row">
        <div class="form-group">
          <label for="inicio">Fecha de inicio:</label>
          <input type="date" id="inicio" name="inicio" required />
        </div>
        <div class="form-group">
          <label for="fecha_fin">Fecha de fin:</label>
          <input type="date" id="fecha_fin" name="fecha_fin" required />
        </div>
        <div class="form-group">
          <label for="personas">Cantidad de personas:</label>
          <input type="number" id="personas" name="personas" required />
        </div>
        <div class="form-group">
          <label for="tipo_de_vehiculo">Tipo de vehículo:</label>
          <select class="form_vehiculo" id="tipo_de_vehiculo" name="tipo_de_vehiculo" required>
            <option value="Casilla">Casilla</option>
            <option value="Auto">Auto</option>
            <option value="Colectivo">Colectivo</option>
            <option value="Camioneta">Camioneta</option>
            <option value="Motorhome">Motorhome</option>
          </select>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group">
          <label>Características de la parcela:</label>
          <div>
            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox1" value="fogon">
            <label for="inlineCheckbox1">Con Fogón</label>
          </div>
          <div>
            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox2" value="tomaElectrica">
            <label for="inlineCheckbox2">Con Toma Eléctrica</label>
          </div>
          <div>
            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox3" value="sombra">
            <label for="inlineCheckbox3">Con Sombra</label>
          </div>
          <div>
            <input class="form-check form-check-inline" name="caracteristicas[]" type="checkbox" id="inlineCheckbox4" value="agua">
            <label for="inlineCheckbox4">Con Agua</label>
          </div>
        </div>
      </div>
      <div class="form-row">
        <button type="submit" class="btn btn-success">Buscar</button>
      </div>
    </form>
    <br>
    <?php if(!empty($mostrar) && $mostrar==true):?>
        <p class="alert alert-danger"><?= htmlspecialchars($mensaje)?></p>
    <?php else: ?>

    <?php endif; ?>

