<main>
    <section class="informes" id="content">
        <h2>Generación de Informes</h2>
        <form id="formulario-informes">
            <label for="fecha">Seleccionar Fecha:</label>
            <input type="date" name="fecha" id="fecha" required>

            <label for="tipo_informe">Tipo de Informe:</label>
            <select name="tipo_informe" id="tipo_informe">
                <option value="reservas">Cantidad de reservas</option>
                <option value="acampantes">Cantidad de personas acampando</option>
                <option value="ocupacion">Nivel de ocupación</option>
                <option value="ingresos">Ingresos generados</option>
            </select>

            <button type="submit">Generar Informe</button>
        </form>

        <div id="resultado-informe" class="resultado-informe"></div>
    </section>
</main>
<script src="js/informes.js"></script>
