<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"
    />
    <link rel="stylesheet" href="./estilos/estilo.css" />
    <link rel="stylesheet" href="./estilos/formulario.css" />
    <link rel="shortcut icon" href="https://www.turismoloberia.gov.ar/sites/default/files/logo_footer_iso.png" type="image/png" />
   
    <title>Reservaciones Arenas Verdes - Inicio</title>
  </head>
  <body>
    <header>
  <?php include 'nav.phtml'; ?>
</header>
    <script src="https://www.turismoloberia.gov.ar/sites/all/themes/contrib/bootstrap/js/bootstrap.js?sm6all"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<!--<script src="./js/formulario.js"></script> -->

  </body>
</html>
