<?php include 'header.phtml'; ?>
<?php if ($dispo == false): ?>
  <?php include 'cartel_baja_disponibilidad.phtml'; ?>
<?php else: ?>
  <br>
<?php endif; ?>
<main>
  <section class="introduccion" id="content">
    <h1>Bienvenido a Arenas Verdes</h1>
    <p>
      Explora nuestras opciones de reservaciones, descubre nuestras tarifas y
      encuentra respuestas a tus preguntas. Disfruta de una experiencia única
      en Arenas Verdes.
    </p>

    <h1>Arenas Verdes, las playas de Lobería, te esperan</h1>
    <p>
      Para disfrutar de un descanso natural, en contacto con la naturaleza y la calidez de los loberenses.
      A la altura del km 108,5 de la ruta 88, se encuentra el acceso al Balneario Arenas Verdes, Partido de Lobería.
      Un acceso de 7 km. de camino entoscado lo llevará hasta un bosque con árboles de gran edad.
    </p>
    <p>
      El Balneario Arenas Verdes comprende unas 170 hectáreas y cuenta con unos 900 lotes aproximadamente.
      Es un lugar agreste dentro del Partido de Lobería que ofrece Sol y Playa y distintas opciones de alojamiento.
      Es un lugar pequeño, en desarrollo y visitado por loberenses y turistas de la provincia.
    </p>
    <p>
      Cuenta con unos 15 pobladores estables. Y recibe en verano a unas 4000 personas durante los fines de semana.
      Recientemente fue declarada “Paisaje Protegido de Interés Provincial” por Ley 15141.
    </p>
    <p>
      El 28 de diciembre de 1953 es considerada como fecha fundacional de la localidad Arenas Verdes; fecha en que se
      aprueba el plano de geodesia Nro. 61-56-53, a través del cual se autoriza el loteo de la parcela 731, propiedad
      del
      Sr. Meyer Kupfershmidt, hecho que da origen al poblado con el nombre de “MAR DEL ORO”, luego denominado
      popularmente Arenas Verdes.
    </p>

    <h2>Para Disfrutar Arenas Verdes</h2>
    <p>
      Arenas Verdes presenta varias alternativas además de disfrutar a full del sol, la playa y las olas.
    </p>
    <p>
      Lobería es un lugar privilegiado para la observación de aves, ya que cuenta con distintos ambientes: río, sierras,
      mar, arroyos y planicies.
    </p>
    <p>
      A medida que más personas se sumen a observar las aves silvestres, seguramente se encontrarán más especies en la
      zona.
      La costa de Lobería es un refugio importante para las aves playeras. El camino costero Arenas Verdes - Costa
      Bonita es muy
      recomendable para la observación. En el recorrido encontrarás el mirador de aves realizado por el Club de
      Observadores
      de Aves (COA).
    </p>
    <p>
      Por eso te invitamos a descargar una info para que puedas conocer a nuestros visitantes, visitar el mirador de las
      aves y
      llevarte imágenes de quienes nos visitan y siguen su camino.
    </p>
    <a href="reservacion.html" class="boton-reserva">Reservar ahora</a>
  </section>

</main>

<?php
include 'whatsapp.phtml';
include 'footer.phtml';
?>