 <!--SECCION DEL FORMULARIO DE LOGIN-->
 <div class="overlay" id="overlay">
      <div class="form-container">
        <h2>Inicio sesión</h2>
        <form id="loginForm" method="$_POST">
         
          <input
            type="email"
            id="email"
            name="email"
            placeholder="E-mail"
            required
          />
          <input
            type="password"
            id="password"
            name="password"
            placeholder="password"
            required
          />
          <button type="submit">Iniciar sesión</button>
          <button type="button" class="cancel" id="cancelBtn">Cancelar</button>
        </form>
      </div>
    </div>