<!-- Incluye Bootstrap CSS en la cabecera de tu documento -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

<nav class="navbar navbar-expand-lg navbar">
  <div class="container-fluid">
    <!-- Logo -->
    <a href="https://www.turismoloberia.gov.ar" class="navbar-brand">
      <img src="./img/logos/logo_loberia.png" alt="Logo Lobería" class="logo" />
    </a>
    
    <!-- Botón de menú en pantallas pequeñas -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!-- Enlaces del menú -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="home">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="reservacion">Reservación</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="precios">Precios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="preguntas">Preguntas Frecuentes</a>
        </li>
 
      </ul>
        <!-- Botón de Login para registrarse -->
     <button class="btn_login" id="loginBtn" type="button">
          <img width="20px" src="./img/logos/login_1.png" alt="Login" />
        </button>
      </div>
    </div>
    <?php
    include('form.phtml');
    include('login.phtml');