<nav class="navbar navbar-expand-md navbar">
  <div class="container-fluid">
    <!-- Logo -->
    <a href="https://www.turismoloberia.gov.ar" class="navbar-brand">
      <img src="./img/logos/logo_loberia.png" alt="Logo Lobería" class="logo" />
    </a>
    <!-- Botón de menú en pantallas pequeñas -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Enlaces del menú -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="home">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="parcelas">Parcelas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="seccion_reservacion">Reservación</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="precios">Precios</a>
        </li>
        <?php if (($this->logueado) && (($this->rol == "admin") || ($this->rol == "super"))): ?>
          <li class="nav-item">
            <a class="nav-link" href="crt_parcelas">Control Parcelas</a>
          </li>
           <?php endif; ?>
          <?php if (($this->logueado) && ($this->rol == "super")): ?>
          <li class="nav-item">
            <a class="nav-link" href="users">Usuarios</a>
          </li>
        <?php endif; ?>
        <li class="nav-item">
          <a class="nav-link" href="preguntas">Preguntas Frecuentes</a>
        </li>
     
      <!-- Botón de Login para registrarse -->
      <?php if (!$this->logueado): ?>

        <div class="auth-buttons">
         <li class="nav-item">
          <!-- Botón Iniciar Sesión -->
          <button type="button" class="btn-auth btn-login" data-bs-toggle="modal" data-bs-target="#loginModal">
            Iniciar Sesión
          </button>
          </li>

          <!-- Botón Registrarse -->
          <li class="nav-item">
          <button type="button" class="btn-auth btn-register" data-bs-toggle="modal" data-bs-target="#regisModal">
            Registrarse
          </button>
          </li>
        </div>
      <?php else: ?>
        <div class="auth-buttons">
          <!-- Icono de perfil -->
        <li class="nav-item">
          <a href="perfil" class="btn-auth btn-profile">
            <i class="bi bi-person-circle"></i>
          </a>
      </li>
          <!-- Botón Logout -->
    <li class="nav-item">
   <a class="btn-auth btn-logout" href="logout">Logout</a>
          </li>
        </div>
      <?php endif; ?>
    </div>
  

 </ul>
  </div>
</nav>


  <!-- Modal login-->
  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="loginModalLabel">Inicio sesión</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

          <form id="loginForm" action="auth" method="post" class="form-container">
            <div>
              <input type="email" name="email" placeholder="E-mail" required />
              <input type="password" id="password" name="password" placeholder="password" required />
            </div>

            <div>
              <a href="#" data-bs-toggle="modal" data-bs-target="olvideModal">Olvidé mi contraseña</a>
              <button type="submit" class="btn btn-primary" id="loginBtn">Iniciar sesión</button>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>

          </form>
        </div>
        <div class="modal-footer">

        </div>
      </div>
    </div>
  </div>

  <!-- Modal olvide mi contraseña -->
  <div class="modal fade" id="olvideModal" tabindex="-1" aria-labelledby="olvideModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="olvideModalLabel">Olvidé mi contraseña</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

          <form id="olvideForm" action="olvideContraseña" method="post" class="form-container">
            <div>
              <input type="email" name="email" placeholder="E-mail" required />

              <button type="submit" class="btn btn-primary">Enviar</button>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>

          </form>
        </div>
        <div class="modal-footer">

        </div>
      </div>
    </div>
  </div>



  <!-- Modal registro de usuaruio -->
  <div class="modal fade" id="regisModal" tabindex="-1" aria-labelledby="regisModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="regisModalLabel">Registro de Usuario</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="registrationForm" action="register" method="post" class="form-container">

            <input type="text" id="name" name="nombre" placeholder="Nombre" required />

            <input type="text" id="apellido" name="apellido" placeholder="Apellido" required />
            <input type="number" id="dni" name="dni" placeholder="DNI" required />
            <input type="number" min="00000" id="phone" name="phone" placeholder="Celular" required />
            <input type="password" id="pass" name="password" placeholder="Contraseña" required />
            <input type="email" id="email" name="email" placeholder="E-mail" required />
            <input type="text" id="localidad" name="localidad" placeholder="Localidad" required />
            <button type="submit" class="btn btn-primary">Registrarse</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          </form>
        </div>
        <div class="modal-footer">


        </div>
      </div>
    </div>
  </div>