<?php include 'header.phtml'; ?>
<?php include 'nav.phtml'; ?>

<?php if ($dispo == false): ?>
  <?php include 'cartel_baja_disponibilidad.phtml'; ?>
<?php else: ?>
<?php endif; ?>
<main>
  <section class="introduccion" id="content">
    <h1>TARIFAS BASE DE CAMPAMENTO</h1>
    <table class="table">
      <tbody>
        <thead>
          <th></th>
          <th>NO RESIDENTES</th>
          <th>RESIDENTES DE LOBERIA</th>
          <th></th>
        </thead>
        <tr>
          <td>Menores 4 años</td>
          <td>sin costo</td>
          <td>sin costo</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
        <tr>
          <td>de 4 a 12 años</td>
          <td>$ 4700</td>
          <td>$ 500</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
        <tr>
          <td>Mayores 12 años</td>
          <td>$ 8500</td>
          <td>$ 900</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
        <tr>
          <td>Vehiculo</td>
          <td>$ 1200</td>
          <td>$ 300</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
        <tr>
          <td>Estadia diaria Casillas</td>
          <td>$ 3000</td>
          <td>$ 1300</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
        <tr>
          <td>Estadia Mensual Casillas</td>
          <td>$ 60000</td>
          <td>$ 30000</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
        <tr>
          <td>Pasar el día</td>
          <td>$ 1300</td>
          <td>$ 400</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
        <tr>
          <td>Uso de duchas</td>
          <td>$ 900</td>
          <td>$ 250</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
        <tr>
          <td>Uso de sanitarios</td>
          <td>$ 200</td>
          <td>$ 100</td>
          <?php if(($this->logueado)&&($this->rol == "admin")): ?>
          <td><button class="btn btn-primary">Editar</button></td>
          <?php endif; ?>
        </tr>
      </tbody>
    </table>
    <p>*Las tarifas son por día y por persona</p>
    <h2>Simulador de precios: </h2>
    <form class="form-inline" action="simular_precios" method="post">
      <div class="form-group">
        <label for="personas">Personas: </label>
        <label> Menores de 4 años: </label>
        <input name="edad_ninos4" type="number" min="00"
          max="20" width="20%" id="ninos">
        <label> Mayores de 4 hasta 12 años: </label>
        <input name="edad_ninos12" type="number" min="00"
          max="20" width="20%" id="ninos_m">
        <label> Mayores de 12 años: </label>
        <input name="edad_ninos20" type="number" min="00"
          max="20" width="20%" id="ninos">
      </div>
      <div class="form-group">
        <label for="estancia">Dias de estancia:</label>
        <input name="estancia" type="number" min="00"
          max="100" class="form-control">
      </div>
      <div class="form-group">
          <label for="personas">Procedencia:</label>
            <select class="form-control" name="localidad" id="exampleFormControlSelect1">
              <option value="loberia">Loberia</option>
              <option value="necochea">Necochea</option>
              <option value="tandil">Tandil</option>
              <option value="mar_del_plata">Mar del Plata</option>
              <option value="miramar">Miramar</option>
              <option value="balcarce">Balcarce</option>
              <option value="otra">Otra</option>
            </select>
      </div>
      <br>
      <div class="checkbox">
        <label>Caracteristicas adicionales: </label>
        <label><input name="caracteristicas[]" type="checkbox" value="ducha"> Ducha</label>
        <label><input name="caracteristicas[]" type="checkbox" value="sanitario"> Sanitario</label>
      </div>
      <br>
      <div class="form-group">
        <label for="tipo_de_vehiculo">Tipo de vehículo:</label>
        <select class="form_vehiculo" id="tipo_de_vehiculo" name="tipo_de_vehiculo" required>
          <option value="sin_vehiculo">Sin vehiculo</option>
          <option value="auto">Auto</option>
          <option value="camioneta">Camioneta</option>
          <option value="motorhome">Motorhome</option>
          <option value="casilla">Casilla</option>
        </select>
      </div>
      <div>
      </div>
      <button type="submit" class="btn btn-primary">Calcular</button>
    </form>
  </section>
  <!-- SECCION PARA MOSTRAR LAS PARCELAS DISPONIBLES -->
  <div class="container">
    <?php if (!empty($precio_final)): ?>
      <div class="alert alert-success">
        <p>El precio de la reserva segun sus preferencias es de: <?= htmlspecialchars($precio_final) ?>
      </div>
  </div>
<?php else: ?>
  <br>
<?php endif; ?>

<?php
include 'whatsapp.phtml';
include 'footer.phtml';
?>