<?php include 'header.phtml'; ?>
<main>
  <br>
  <section class="introduccion blurred-content" id="content">
    <h2>Simulador de precios: </h2>
    <form class="form-inline" action="simular_precios" method="post">
      <div class="form-group">
        <label for="personas">Personas: </label>
        <label> Menores de 4 años: </label>
        <input name="edad_ninos4" type="number" min="00"
          max="20" width="20%" id="ninos">
        <label> Mayores de 4 hasta 12 años: </label>
        <input name="edad_ninos12" type="number" min="00"
          max="20" width="20%" id="ninos_m">
        <label> Mayores de 12 años: </label>
        <input name="edad_ninos20" type="number" min="00"
          max="20" width="20%" id="ninos">
      </div>
      <div class="form-group">
        <label for="estancia">Dias de estancia:</label>
        <input name="estancia" type="number" min="00"
          max="100" class="form-control">
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="residentes" id="exampleRadios1" value="1" checked>
        <label class="form-check-label" for="exampleRadios1">
          Si        
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="residentes" id="exampleRadios2" value="0">
        <label class="form-check-label" for="exampleRadios2">
          No
        </label>
      </div>
      <div class="checkbox">
        <label>Caracteristicas adicionales: </label>
        <label><input name="caracteristicas[]" type="checkbox" value="ducha"> Ducha</label>
        <label><input name="caracteristicas[]" type="checkbox" value="sanitario"> Sanitario</label>
        <label><input name="caracteristicas[]" type="checkbox" value="casilla">Espacio para casilla</label>
        <label><input name="caracteristicas[]" type="checkbox" value="vehiculo"> Espacio para vehiculo </label>
      </div>
      <div>
      </div>
      <button type="submit" class="btn btn-primary">calcular</button>
    </form>
  </section>
  <!-- SECCION PARA MOSTRAR LAS PARCELAS DISPONIBLES -->
  <div class="container">
      <?php if (!empty($precio_final)): ?>
          <div class="alert alert-success">
              <p>El precio de la reserva segun sus preferencias es de: <?= htmlspecialchars($precio_final) ?>
          </div>
          </div>
      <?php else: ?> 
        <br>
      <?php endif; ?>
</main>
<?php

include 'whatsapp.phtml';
include 'footer.phtml';

?>