<?php include 'header.phtml'; ?>
<?php include 'nav.phtml'; ?>
<?php if ($dispo == false): ?>
    <?php include 'cartel_baja_disponibilidad.phtml'; ?>
  <?php else: ?>
    <br>
  <?php endif; ?>
<main>
  <section class="introduccion" id="content">
    <h1 style="align-items: center;">Haz tu Reserva Hoy </h1>
    
      
    </div>
   
    

  </section>
  <?php
      include 'formParaReservacion.phtml';
    ?>

</main>

<?php

include 'whatsapp.phtml';
include 'footer.phtml';

?>