<?php include 'header.phtml'; ?>
<?php include 'nav.phtml'; ?>
<?php if ($dispo == false): ?>
  <?php include 'cartel_baja_disponibilidad.phtml'; ?>
<?php else: ?>
  <br>
<?php endif; ?>
<main>
  <section class="introduccion" id="content">
  <?php if ($this->rol=='admin'): ?>
   <h2>Control de Reservaciones sin confirmar:</h2>  
   <br>
   <?php include 'controlReservas.phtml'; ?>   
   <br>
  <?php endif; ?>
  <?php if ($this->logueado): ?>
   <?php include 'misReservas.phtml'; ?>   
  <?php endif; ?>
    <h2 style="text-align: center;">Haz tu Reserva Hoy Mismo </h2>
    <br>
    <?php
    include 'formParaReservacion.phtml';
    ?>
  </section>
</main>

<?php

include 'whatsapp.phtml';
include 'footer.phtml';

?>